/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PoliticaDePrivacidadRouteImport } from './routes/politica-de-privacidad'
import { Route as TerminosYCondicionesRouteImport } from './routes/terminos-y-condiciones'
import { Route as EquipoIndexRouteImport } from './routes/equipo.index'
import { Route as EquipoSlugRouteImport } from './routes/equipo.$slug'
import { Route as ServiciosIndexRouteImport } from './routes/servicios.index'
import { Route as ServiciosSlugRouteImport } from './routes/servicios.$slug'
import { Route as ServiciosBancaYFinanzasRouteImport } from './routes/servicios.banca-y-finanzas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadRoute = PoliticaDePrivacidadRouteImport.update({
  id: '/politica-de-privacidad',
  path: '/politica-de-privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosYCondicionesRoute = TerminosYCondicionesRouteImport.update({
  id: '/terminos-y-condiciones',
  path: '/terminos-y-condiciones',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipoIndexRoute = EquipoIndexRouteImport.update({
  id: '/equipo/',
  path: '/equipo/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipoSlugRoute = EquipoSlugRouteImport.update({
  id: '/equipo/$slug',
  path: '/equipo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosIndexRoute = ServiciosIndexRouteImport.update({
  id: '/servicios/',
  path: '/servicios/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosSlugRoute = ServiciosSlugRouteImport.update({
  id: '/servicios/$slug',
  path: '/servicios/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosBancaYFinanzasRoute = ServiciosBancaYFinanzasRouteImport.update({
  id: '/servicios/banca-y-finanzas',
  path: '/servicios/banca-y-finanzas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/terminos-y-condiciones': typeof TerminosYCondicionesRoute
  '/equipo/$slug': typeof EquipoSlugRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/servicios/banca-y-finanzas': typeof ServiciosBancaYFinanzasRoute
  '/equipo/': typeof EquipoIndexRoute
  '/servicios/': typeof ServiciosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/terminos-y-condiciones': typeof TerminosYCondicionesRoute
  '/equipo/$slug': typeof EquipoSlugRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/servicios/banca-y-finanzas': typeof ServiciosBancaYFinanzasRoute
  '/equipo': typeof EquipoIndexRoute
  '/servicios': typeof ServiciosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/terminos-y-condiciones': typeof TerminosYCondicionesRoute
  '/equipo/$slug': typeof EquipoSlugRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/servicios/banca-y-finanzas': typeof ServiciosBancaYFinanzasRoute
  '/equipo/': typeof EquipoIndexRoute
  '/servicios/': typeof ServiciosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/politica-de-privacidad'
    | '/terminos-y-condiciones'
    | '/equipo/$slug'
    | '/servicios/$slug'
    | '/servicios/banca-y-finanzas'
    | '/equipo/'
    | '/servicios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/politica-de-privacidad'
    | '/terminos-y-condiciones'
    | '/equipo/$slug'
    | '/servicios/$slug'
    | '/servicios/banca-y-finanzas'
    | '/equipo'
    | '/servicios'
  id:
    | '__root__'
    | '/'
    | '/politica-de-privacidad'
    | '/terminos-y-condiciones'
    | '/equipo/$slug'
    | '/servicios/$slug'
    | '/servicios/banca-y-finanzas'
    | '/equipo/'
    | '/servicios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PoliticaDePrivacidadRoute: typeof PoliticaDePrivacidadRoute
  TerminosYCondicionesRoute: typeof TerminosYCondicionesRoute
  EquipoSlugRoute: typeof EquipoSlugRoute
  ServiciosSlugRoute: typeof ServiciosSlugRoute
  ServiciosBancaYFinanzasRoute: typeof ServiciosBancaYFinanzasRoute
  EquipoIndexRoute: typeof EquipoIndexRoute
  ServiciosIndexRoute: typeof ServiciosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidad': {
      id: '/politica-de-privacidad'
      path: '/politica-de-privacidad'
      fullPath: '/politica-de-privacidad'
      preLoaderRoute: typeof PoliticaDePrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos-y-condiciones': {
      id: '/terminos-y-condiciones'
      path: '/terminos-y-condiciones'
      fullPath: '/terminos-y-condiciones'
      preLoaderRoute: typeof TerminosYCondicionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipo/': {
      id: '/equipo/'
      path: '/equipo'
      fullPath: '/equipo/'
      preLoaderRoute: typeof EquipoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipo/$slug': {
      id: '/equipo/$slug'
      path: '/equipo/$slug'
      fullPath: '/equipo/$slug'
      preLoaderRoute: typeof EquipoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/': {
      id: '/servicios/'
      path: '/servicios'
      fullPath: '/servicios/'
      preLoaderRoute: typeof ServiciosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/$slug': {
      id: '/servicios/$slug'
      path: '/servicios/$slug'
      fullPath: '/servicios/$slug'
      preLoaderRoute: typeof ServiciosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/banca-y-finanzas': {
      id: '/servicios/banca-y-finanzas'
      path: '/servicios/banca-y-finanzas'
      fullPath: '/servicios/banca-y-finanzas'
      preLoaderRoute: typeof ServiciosBancaYFinanzasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PoliticaDePrivacidadRoute: PoliticaDePrivacidadRoute,
  TerminosYCondicionesRoute: TerminosYCondicionesRoute,
  EquipoSlugRoute: EquipoSlugRoute,
  ServiciosSlugRoute: ServiciosSlugRoute,
  ServiciosBancaYFinanzasRoute: ServiciosBancaYFinanzasRoute,
  EquipoIndexRoute: EquipoIndexRoute,
  ServiciosIndexRoute: ServiciosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
