/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EquipoIndexRouteImport } from './routes/equipo.index'
import { Route as EquipoSlugRouteImport } from './routes/equipo.$slug'
import { Route as ServiciosBancaYFinanzasRouteImport } from './routes/servicios.banca-y-finanzas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipoIndexRoute = EquipoIndexRouteImport.update({
  id: '/equipo/',
  path: '/equipo/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipoSlugRoute = EquipoSlugRouteImport.update({
  id: '/equipo/$slug',
  path: '/equipo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosBancaYFinanzasRoute = ServiciosBancaYFinanzasRouteImport.update({
  id: '/servicios/banca-y-finanzas',
  path: '/servicios/banca-y-finanzas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/equipo/$slug': typeof EquipoSlugRoute
  '/servicios/banca-y-finanzas': typeof ServiciosBancaYFinanzasRoute
  '/equipo/': typeof EquipoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/equipo/$slug': typeof EquipoSlugRoute
  '/servicios/banca-y-finanzas': typeof ServiciosBancaYFinanzasRoute
  '/equipo': typeof EquipoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/equipo/$slug': typeof EquipoSlugRoute
  '/servicios/banca-y-finanzas': typeof ServiciosBancaYFinanzasRoute
  '/equipo/': typeof EquipoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/equipo/$slug' | '/servicios/banca-y-finanzas' | '/equipo/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/equipo/$slug' | '/servicios/banca-y-finanzas' | '/equipo'
  id:
    | '__root__'
    | '/'
    | '/equipo/$slug'
    | '/servicios/banca-y-finanzas'
    | '/equipo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EquipoSlugRoute: typeof EquipoSlugRoute
  ServiciosBancaYFinanzasRoute: typeof ServiciosBancaYFinanzasRoute
  EquipoIndexRoute: typeof EquipoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipo/': {
      id: '/equipo/'
      path: '/equipo'
      fullPath: '/equipo/'
      preLoaderRoute: typeof EquipoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipo/$slug': {
      id: '/equipo/$slug'
      path: '/equipo/$slug'
      fullPath: '/equipo/$slug'
      preLoaderRoute: typeof EquipoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/banca-y-finanzas': {
      id: '/servicios/banca-y-finanzas'
      path: '/servicios/banca-y-finanzas'
      fullPath: '/servicios/banca-y-finanzas'
      preLoaderRoute: typeof ServiciosBancaYFinanzasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EquipoSlugRoute: EquipoSlugRoute,
  ServiciosBancaYFinanzasRoute: ServiciosBancaYFinanzasRoute,
  EquipoIndexRoute: EquipoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
