/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiciosBancaYFinanzasRouteImport } from './routes/servicios.banca-y-finanzas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosBancaYFinanzasRoute = ServiciosBancaYFinanzasRouteImport.update({
  id: '/servicios/banca-y-finanzas',
  path: '/servicios/banca-y-finanzas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/servicios/banca-y-finanzas': typeof ServiciosBancaYFinanzasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/servicios/banca-y-finanzas': typeof ServiciosBancaYFinanzasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/servicios/banca-y-finanzas': typeof ServiciosBancaYFinanzasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/servicios/banca-y-finanzas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/servicios/banca-y-finanzas'
  id: '__root__' | '/' | '/servicios/banca-y-finanzas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServiciosBancaYFinanzasRoute: typeof ServiciosBancaYFinanzasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/banca-y-finanzas': {
      id: '/servicios/banca-y-finanzas'
      path: '/servicios/banca-y-finanzas'
      fullPath: '/servicios/banca-y-finanzas'
      preLoaderRoute: typeof ServiciosBancaYFinanzasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServiciosBancaYFinanzasRoute: ServiciosBancaYFinanzasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
